#!/usr/bin/expect -f

set timeout 30
set server_ip [lindex $argv 0]
set server_user [lindex $argv 1]
set server_path [lindex $argv 2]
set password "ZDLT@20250702"

spawn ssh ${server_user}@${server_ip} "cd ${server_path} && git pull"

expect {
    "password:" {
        send "$password\r"
        expect eof
    }
    "yes/no" {
        send "yes\r"
        expect "password:"
        send "$password\r"
        expect eof
    }
    eof
} 